export const environment = {
  SUPABASE_URL: 'https://fsrptlzaqjkcutoiivjr.supabase.co',
  API_KEY:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzcnB0bHphcWprY3V0b2lpdmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTYxNjA4MjIsImV4cCI6MjAzMTczNjgyMn0.EGyx9-GkmEjeFx78c8P1Ou4JHBO5rXEwD274isJMkmQ',
  SECRET_KEY:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzcnB0bHphcWprY3V0b2lpdmpyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxNjE2MDgyMiwiZXhwIjoyMDMxNzM2ODIyfQ.bRkzdRiQBJGfyc49L7wZhfA0V-uV-nam_AAX_F0S4vI',
};
